services:
    back:
        container_name: back
        build:
            dockerfile: Dockerfile
            context: ./back
        env_file: ./.env
        volumes:
            - backVolume:/app/
        networks:
            - transcenet
        depends_on:
            - dev-db
        ports:
            - "5555:5555"
            - "3333:3333"
        restart: always

    dev-db:
        container_name: dev-db
        image: postgres:15
        ports:
            - "5432:5432"
        env_file: ./.env
        networks:
            - transcenet
        restart: always

volumes:

    backVolume:
        driver: local
        driver_opts:
            type: 'none'
            device: '$PWD/back'
            o: bind

networks:
  transcenet:
    driver: bridge
